version: '3.8'

networks:
  Test_Network:
    external: true

services:
  report_generator_service:
    container_name: report_generator_service
    image: reportgeneratorservice:latest
    networks:
      - Test_Network
      
      