#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["ContactService.API/ContactService.API.csproj", "ContactService.API/"]
COPY ["ContactService.Infrastructure/ContactService.Infrastructure.csproj", "ContactService.Infrastructure/"]
COPY ["ContactService.Application/ContactService.Application.csproj", "ContactService.Application/"]
COPY ["ContactService.Domain/ContactService.Domain.csproj", "ContactService.Domain/"]
RUN dotnet restore "./ContactService.API/./ContactService.API.csproj"
COPY . .
WORKDIR "/src/ContactService.API"
RUN dotnet build "./ContactService.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./ContactService.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ContactService.API.dll"]



#FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
#FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
#WORKDIR /app
#
#COPY ./bin/Release/net8.0/publish .
#ENTRYPOINT ["dotnet", "ContactService.API.dll"]